### ISSUE TITLE
Work through GitHub features

### ISSUE THREAD

**Issue by Trewaters** [aneylon/GitIt#1]
This is testing how to create an issue in GitHub. I am looking at a tutorial on ( https://guides.github.com/activities/hello-world/ ) as a guide of things I should practice using

**Comment by aneylon** [comment]
So, looks like I can just type in a comment and tell it to close the issue.

**Comment by aneylon** [comment]
But can I add comments after closing?

**Comment by aneylon** [comment]
Yep, and reopen.

**Comment by Trewaters** [comment]
Thanks for closing the pull request.
